import GanttSvgCanvas from "../util/GanttSvgCanvas";
import { GanttCellState } from "../view/GanttCellState";
export default class ganttShape {
    constructor();
    private initStyles;
    init(container: SVGGElement): void;
    create(container: any): SVGGElement;
    createSvg(): SVGGElement;
    redraw(): void;
    doRedrawShape(canvas: GanttSvgCanvas): void;
    beforePaint(canvas: GanttSvgCanvas): void;
    paint(canvas: GanttSvgCanvas): void;
    afterPaint(canvas: GanttSvgCanvas): void;
    paintShape(canvas: GanttSvgCanvas, x: number, y: number, width: number, height: number): void;
    paintBackground(canvas: GanttSvgCanvas, x: number, y: number, width: number, height: number): void;
    paintForeground(canvas: GanttSvgCanvas, x: number, y: number, width: number, height: number): void;
    configureCanvas(c: GanttSvgCanvas): void;
    createCanvas(): GanttSvgCanvas;
    apply(state: GanttCellState): void;
    destroy(): void;
    setCursor(cursor?: string): void;
    clear(): void;
    node: SVGGElement;
    bounds: any;
    stroke: string;
    strokeWidth: number;
    opacity: number;
    cursor: string;
    fillColor: string;
    state: GanttCellState;
}
